### ISSUE TITLE
[tasks2022]: PlotR - add bands between prediction uncertainty lines

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/plotr#1]
original ticket: https://github.com/INWT/mpi-plotr/issues/65

Additionally:
- [x] enable/disable band between prediction uncertainty lines
- [x] choose colour and opacity for the band (default: colour of prediction with higher opacity)

-> In seperate issue.

_Originally posted by @arunge in https://github.com/INWT/mpi-plotr/issues/48#issuecomment-933316583_

Maybe we don't need "enable/disable" option: setting opacity (an alpha parameter) to 0 is like disabling ...

For example it could look like:

![image](https://user-images.githubusercontent.com/16759098/217754843-a4f08084-05b2-4386-833a-29a6f13d9d85.png)

**Comment by arunge** [comment]
@f-lukas You can take this ticket when you have time for it...

**Comment by f-lukas** [comment]
@isomemo - This feature can now also be tested on beta.

**Comment by isomemo** [comment]
@f-lukas I could not find the option in both the main and beta versions.

**Comment by arunge** [comment]
On beta https://isomemoapp.com/app/plotr-beta

- run a model, by default bands are displayed:

![image](https://github.com/Pandora-IsoMemo/plotr/assets/16759098/c4f3cee3-c6a2-42a3-bcc9-52be8573b02b)

- "style" the band under "Style plot": 
  - the option to style the band appears under "Select line": "model uncertainty" (1) at the bottom you can change color and  opacity (2)

![image](https://github.com/Pandora-IsoMemo/plotr/assets/16759098/77d7fc82-156b-45e2-9dff-b03d0edcc933)

**Comment by isomemo** [comment]
@arunge works! thanks!
