### ISSUE TITLE
Cannot select data columns

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/plotr#14]
@arunge For beta version which recently had some fixes I created a simple data file: 
[test.xlsx](https://github.com/Pandora-IsoMemo/plotr/files/10140030/test.xlsx)

After I upload the data I tried to select the data input columns under Run model/Data settings. However, no data columns are listed for input

**Comment by arunge** [comment]
As discussed in our last meeting, with [version 22.12.1](https://github.com/Pandora-IsoMemo/plotr/pull/15) on the [beta app](https://isomemoapp.com/app/plotr-beta),  I added placeholders to remind the user that data must be loaded (by pressing a button)/imported/... .
