### ISSUE TITLE
[tasks 2022] Add credible intervals to table outputs

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/plotr#2]
original in: https://github.com/INWT/mpi-plotr/issues/63

> ... add _credible intervals_ ...
> 
> _Originally posted by @arunge in https://github.com/INWT/mpi-plotr/issues/15#issuecomment-981592536_
> 
> - [x] option to select the credible percents
> - [x] add credible intervals to the output
>

**Comment by arunge** [comment]
- Fit model:
  https://github.com/Pandora-IsoMemo/plotr/blob/805f06e48ee86b4b3f3173b168bd477abfbe4d7f/R/01-predictData.R#L272-L282

- Button: "Predict Y"
  https://github.com/Pandora-IsoMemo/plotr/blob/805f06e48ee86b4b3f3173b168bd477abfbe4d7f/R/01-predictData.R#L44-L62
  - export in "Run Model":
    ![image](https://user-images.githubusercontent.com/16759098/237032390-39941ec1-ffc2-4826-82e2-d568dd5e0e5a.png)
  - export for "Predict Y"
    ![image](https://user-images.githubusercontent.com/16759098/237032964-513a92f4-046d-4e90-a496-be7d48d5ce7e.png)
- Button: "Derive X"
  https://github.com/Pandora-IsoMemo/plotr/blob/805f06e48ee86b4b3f3173b168bd477abfbe4d7f/R/01-predictAdditionalData.R#L100-L122 
  - export for "Derive X"
    ![image](https://user-images.githubusercontent.com/16759098/237033584-e313a6f7-fbb3-4769-9a90-b7f67c142e50.png)

**Comment by arunge** [comment]
@f-lukas As just discussed let us quickly talk about this task together.

**Comment by arunge** [comment]
We discussed this today: the column names for quantiles of SEM and SEM Total 
![image](https://github.com/Pandora-IsoMemo/plotr/assets/16759098/c82f5ddd-8ea5-44ff-802b-959e8035f2e9)

should contain the selected _Credible Interval Coverage_ :

![image](https://github.com/Pandora-IsoMemo/plotr/assets/16759098/71fb5498-1280-414a-be85-33e404865dc5)

Currently the sliders that control the quantile of the exported data (1) and the plot (2) are not dependent.

@isomemo  Should the slider of the export be updated with the value from the slider for the plot?

**Comment by isomemo** [comment]
@arunge no! If the slider in the export interface sets the values in the exported file, then this is also Ok.

**Comment by arunge** [comment]
Column names containing the quantile value (1, from [above plot](https://github.com/Pandora-IsoMemo/plotr/issues/2#issuecomment-1549974054)) were added with [version 23.5.2](https://github.com/Pandora-IsoMemo/plotr/pull/36) to [plotR beta](https://isomemoapp.com/app/plotr-beta).

So I am closing here.
