### ISSUE TITLE
Only Beta online available

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/plotr#27]
@arunge in the Readme (see below) only the Beta online version is being listed. Please list for all apps main and beta versions!

Also the terminology for local installation and help should be the same for all apps. Here titled "Help and installation instructions"

Within the link above again only the beta links. These are repeated two times which is necessary. Under

You can access the App via https://isomemoapp.com/app/plotr-beta

and then again under

You can access the Web App via:

    https://pandoraapp.earth/app/plotr-beta or
    https://isomemoapp.com/app/plotr-beta [this may be slow]

Also, the comment "this may be slow" points to the second link but actually all links remit to the sam relocation. So the comment should be placed above like this: 
You can access the Web App via [this may be quite slow]:

Finally, the instructions to install are then within another link called getting-started

![image](https://user-images.githubusercontent.com/46485054/222444419-860759b6-d73e-4046-85d1-c889d73e2938.png)

![image](https://user-images.githubusercontent.com/46485054/222444318-df555be6-fd26-43d2-82c8-0da54640859a.png)

**Comment by arunge** [comment]
@isomemo Please note
- https://github.com/Pandora-IsoMemo/drat/issues/25#issue-1606941061

regarding the missing links.

**Comment by arunge** [comment]
@isomemo I updated the wikis as described above:
- https://github.com/Pandora-IsoMemo/bmsc-app/wiki
- https://github.com/Pandora-IsoMemo/bpred/wiki
- https://github.com/Pandora-IsoMemo/iso-app/wiki
- https://github.com/Pandora-IsoMemo/osteo-bior/wiki
- https://github.com/Pandora-IsoMemo/plotr/wiki
- https://github.com/Pandora-IsoMemo/resources/wiki
