### ISSUE TITLE
[tasks 2022] add a legend to the all-in-one plot of "Multiple plot"

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/plotr#3]
original in: https://github.com/INWT/mpi-plotr/issues/57

- [x] additionally a legend is not implemented yet in the all-in-one plot of "Multiple plot"Lower priority now, add later, ask for position of the legend

I think, a legend makes only sense if _"all-in-one"_ plot is selected. Names for the legend labels can be taken from the plot names (1). We need new inputs:
- ckeckbox: Show legend 
- input: Position (maybe one of top-left, top-right, bottom-left, bottom-right ?)

See draft:

![image](https://user-images.githubusercontent.com/16759098/217758346-01cba266-fcaf-4da0-819b-bda47667bee8.png)

**Comment by arunge** [comment]
@f-lukas This could also be somthing for you.

**Comment by f-lukas** [comment]
This feature is now on beta and can be tested. The colors in the legend refer to the data points in the figure. This means that the legend is not too long and remains clear. If necessary, the legend could be extended, but this requires a little more effort.

**Comment by isomemo** [comment]
@f-lukas cannot see the feature on beta version.

**Comment by arunge** [comment]
on beta: https://isomemoapp.com/app/plotr-beta

- one needs at least two plots, select "all-in-one-plot", choose a legend position, the legend appears
- of course it makes sense to use different colours for the lines in "Style plot" ...

![image](https://github.com/Pandora-IsoMemo/plotr/assets/16759098/6d91bd3b-168a-4e73-b917-7d5d7f9d05c0)

**Comment by isomemo** [comment]
@arunge works! thanks!
