### ISSUE TITLE
Explaination Issue: importDataUI

### ISSUE THREAD

**Issue by jyr-ai** [Pandora-IsoMemo/plotr#35]
Hi @arunge 

I am currently building a new app call Causal R: https://github.com/Pandora-IsoMemo/CausalR
For Ricardo. I am borrowing some code from the PlotR modules. 

Can I ask you where you make the function `importDataUI`? I try to run the module from here: 
 https://github.com/Pandora-IsoMemo/plotr/blob/main/R/03-uploadFiles.R#L13

BUT it returns an error because it cannot find this function: `importDataUI`.

please advise, thanks so much,

LG,
Jian

**Comment by arunge** [comment]
I extracted the part of this code as a module into a sub-package. You can load the functions `importDataUI` and `importDataServer` into the [Namespace](https://github.com/Pandora-IsoMemo/plotr/blob/805f06e48ee86b4b3f3173b168bd477abfbe4d7f/R/00-NAMESPACE.R#LL3C1-L4C85) after [importing](https://github.com/Pandora-IsoMemo/plotr/blob/805f06e48ee86b4b3f3173b168bd477abfbe4d7f/DESCRIPTION#LL17C6-L17C6) the package `DataTools`.
Please check the code here:
- https://github.com/Pandora-IsoMemo/data-tools/blob/d62f347e6bc9daf6f9b2a982c23aa62dd814ebba/R/02-importData.R#L9
- https://github.com/Pandora-IsoMemo/data-tools/blob/d62f347e6bc9daf6f9b2a982c23aa62dd814ebba/R/02-importData.R#L33

When having the package `DataTools` loaded locally you can test the module by starting the test app of this package with
```R
startApplication()
```

The package is under steady development. Please check for new version here: https://github.com/Pandora-IsoMemo/data-tools/blob/main/NEWS.md
Please, let me know if you have more questions!

**Comment by jan-abel-inwt** [comment]
Can we close this issue @arunge, @policybot2020 ?

**Comment by arunge** [comment]
@policybot2020 in case there are any more questions, please feel free to open a new issue! :slightly_smiling_face:
