### ISSUE TITLE
Predict data not working

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/plotr#40]
@arunge predict data not working. There are two issues:

1) The option Select a file is not working. If I upload multiple files under Predict Response I only see listed the variables for the first file. That is, variables are not updated when I select a different file.

2) I tried to make a prediction and got an error. Below find error message, file, model settings, and predict settings.

![image](https://github.com/Pandora-IsoMemo/plotr/assets/46485054/d3cb7884-ae7e-4f33-8e77-ba61f2b06630)

![image](https://github.com/Pandora-IsoMemo/plotr/assets/46485054/57a17737-4c2b-4e5e-9945-e2b971bc310f)

![image](https://github.com/Pandora-IsoMemo/plotr/assets/46485054/ead6fee7-2a03-423e-880a-764f4cc4aa98)

![image](https://github.com/Pandora-IsoMemo/plotr/assets/46485054/d1a79096-41ef-47be-8a3a-2907c0573444)

[CO2data.xlsx](https://github.com/Pandora-IsoMemo/plotr/files/11969204/CO2data.xlsx)

**Comment by arunge** [comment]
@isomemo I pushed a fix of both issues from [above](https://github.com/Pandora-IsoMemo/plotr/issues/40#issue-1791679380) to the PlotR  [main](https://isomemoapp.com/app/plotr) and [beta](https://isomemoapp.com/app/plotr-beta) branches which is available with version [23.08.0](https://github.com/Pandora-IsoMemo/plotr/pull/41).
