### ISSUE TITLE
URGENT Data upload not working

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/plotr#47]
After loading a file, visualizing data, and pressing "Accept" no option is given under "View the imported file"

**Comment by arunge** [comment]
@isomemo There was an issue with correctly returning filenames from file imports in DataTools. I fixed this in [DataTools](https://github.com/Pandora-IsoMemo/data-tools/issues/104) and with [PlotR version 24.12.0](https://github.com/Pandora-IsoMemo/PlotR/pull/48/commits/cf03c1078aac5b5fe24b0ac86d99bc7fa2b70683) this fix is already online for the [beta version](https://isomemoapp.com/app/plotr-beta). The update of the main branch is on its way.
