### ISSUE TITLE
3 issues

### ISSUE THREAD

**Issue by isomemo** [Pandora-IsoMemo/plotr#9]
@arunge Three issues:

- [x] No warning is now being issued if a model is run without a sufficient number of basis functions. Simply the model is not run
- [x] No option to export a figure plot under the tab "Run Model"
- [x] I created a model had to save it and tried to export the figure under "Style plot". The app then crashed

**Comment by arunge** [comment]
All above issues are fixed within the [new version 22.11.1](https://github.com/Pandora-IsoMemo/plotr/pull/12#issue-1463729597) on [PlotR beta](https://isomemoapp.com/app/plotr-beta):
If one chose a too little number of basis functions the number of basis functions was increased automatically by the model. Now, a notification will pop up that forwards the warning from the model to the app.
